### ISSUE TITLE
Countess on norm difficulty

### ISSUE THREAD

**Issue by LAeRacing** [blizzhackers/autosmurf#12]
I would like the bot to do some countess runs on normal difficulty cause of rune drops and great exp the way down. This can be also be a combination after Tristruns to get more exp until the tristLvl is reached.
Can you add it please? Thanks

**Comment by mf022** [comment]
> This can be also be a combination after Tristruns to get more exp until the tristLvl is reached.

there should be added additional lines in <https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/libs/bots/AutoSmurf.js#L5836-L5847>

```
	if (me.gametype === 1 && (me.diff == 0 && !this.partyLevel(tristLvl))) {
		if (teleportingSorc) {
			D2Bot.printToConsole("I'm the leader, changed script.");
			OnOff.enable("Scripts.Countess");
		} else {
			OnOff.enable("Scripts.MFHelper");
			D2Bot.printToConsole("I'm a follower, changed script.");
		}
```
