### ISSUE TITLE
Team stands at town wp

### ISSUE THREAD

**Issue by sugedog9000** [blizzhackers/autosmurf#16]
My team of 4 joins game, parties up. Leader goes to town wp, looks like it is looking for a wp, and the followers do the same. Than just sit at the wp, and nothing.

I'm sure this is a simple fix, but I've went over everything several times.

**Comment by LAeRacing** [comment]
Hi sugedog9000,
could you plz set in the d2bs.ini file the line to true?
`UseGamePrint=true`

and in the char-config file (sorc would be good) at the very bottom

`Config.AutoBuild.Verbose = true;`
`Config.AutoBuild.DebugMode = true;`

and then start it up again to see more informations whats going on.

**Comment by Daggui** [comment]
> 
> 
> Hi sugedog9000,
> could you plz set in the d2bs.ini file the line to true?
> `UseGamePrint=true`
> 
> and in the char-config file (sorc would be good) at the very bottom
> 
> `Config.AutoBuild.Verbose = true;`
> `Config.AutoBuild.DebugMode = true;`
> 
> and then start it up again to see more informations whats going on.

Hello LAering , i had the same problem, and here what i got now (bot are still lock in town)

https://i.ibb.co/pjJRbc5/kolbot.jpg

Do you have any idea ?
regards

**Comment by jmancherje** [comment]
I am also having this issue except my lead sorc is at the wp the others are just standing at the start of town

**Comment by mf022** [comment]
> I did what you wrote
> 
> https://i.ibb.co/pjJRbc5/kolbot.jpg
> 
> Do you have any idea ?

It seems that your party isn't set up properly.
The other character names are displayed in red color.
