### ISSUE TITLE
Autosmurf not switching to nm

### ISSUE THREAD

**Issue by Vinnyboi** [blizzhackers/autosmurf#18]
Everything is working fine except that its not going to nightmare. 

Any clues ?

Big thx!!

**Comment by killersquad235** [comment]
Same Problem here!
I manually clicked on nm than and it works!

**Comment by Ricola3D** [comment]
> 
> 
> Same Problem here!
> I manually clicked on nm than and it works!
> 
> Edit:
> Seems solved in the Closed Issue Area.
> You must set the Difficulty on your Profiles to Highest.

Ty, updating the setup guide with it would be nice for next people to use it :)
