### ISSUE TITLE
Follower left behind

### ISSUE THREAD

**Issue by MoneyMoney33** [blizzhackers/autosmurf#19]
When I'm in act 2, say my leader and another character got the dry hills way point, but one of the smurfs had not quite gotten there before the team left. When it joins the next game the characters are stuck because the follower goes the exit of act 2, while the other ones take the waypoint of dry hills an they "wait" for each other until they time out.

How do I make them all go to the lowest part each game? that way my characters aren't getting separated and stuck?

**Comment by mf022** [comment]
you can adjust manually the difference between the autosmurf characters.
