### ISSUE TITLE
Is it possible to change teamsize into >4 ?

### ISSUE THREAD

**Issue by kk1216** [blizzhackers/autosmurf#20]
I am stuck in making the teamsize > 4,
it works smoothly at 4, but it doesn't work when teamsize is more 4.
What should I do? or teamsize can only run under 4?

**Comment by MoneyMoney33** [comment]
What is happening when the team size is > 4 that it is not running smooth?

**Comment by mf022** [comment]
> 
> 
> What is happening when the team size is > 4 that it is not running smooth?

if they don't, the real reason maybe the d2 server restriction for running more accounts/characters from same IP.
