### ISSUE TITLE
2 of 7 bots stuck in town in act 1 normal (7 players team)

### ISSUE THREAD

**Issue by tapakahxp** [blizzhackers/autosmurf#21]
They just stuck and waiting for nothing.
I was trying to start my own local TCP/IP game.
Cold sorc  **1 stuck in town**
Lighting sorc
Fire sorc
Barb
Pally  **stuck in town**

Both Cold sorcs have same build - Blizzard
I've added archive with autosmurf and my local savegames, can somebody help ?
[LocalAutoSmurf.zip](https://github.com/blizzhackers/autosmurf/files/4691614/LocalAutoSmurf.zip)

**Comment by mf022** [comment]
Is the party set correctly?
Lines <https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/D2BotFollow.dbj#L31-L33> is according to your leader's profile name?
