### ISSUE TITLE
Nightmare, 4 of them are mf, one stay in a5

### ISSUE THREAD

**Issue by ayanamireipl** [blizzhackers/autosmurf#22]
So as tittle say, 2 sos, barb pal, making a mf. (60/70lvl) necro stay in a5 and do nothing... All quest's are the same. From a1 norm to a5 nightmare, all be good. Waiting for boo and more. But now 4 of them makes mf run (Andy mef.....) but nec only stay in a5... What is wrong?

**Comment by mf022** [comment]
party settings are ok on latest runs on Nightmare?
