### ISSUE TITLE
Kolbot Autosmurf 4 bot/stay in town

### ISSUE THREAD

**Issue by Daggui** [blizzhackers/autosmurf#24]
Hello guys
i got some problem to set up the autosmurf script.
Atm my bot are staying in town a1 normal close to the wp
The leader is saying this : https://ibb.co/whMwBVj
the follower this : https://ibb.co/sPZMdfs
The first problem is they stay in wp a1
the second problem is they don"t party
Anyone has an idea ?
Thanks for your time and help

**Comment by Daggui** [comment]
![autosmurf bug](https://user-images.githubusercontent.com/66337082/83782330-f342d900-a68f-11ea-8319-2e0110c985ed.jpg)
 i moove step by step but i'm stuck here

**Comment by mf022** [comment]
> the second problem is they don"t party

something is wrong in your config.



> Atm my bot are staying in town a1 normal close to the wp

if autosmurf party isn't realized, no quest will e done.
