### ISSUE TITLE
Using with Classic D2

### ISSUE THREAD

**Issue by zorbiusgaming** [blizzhackers/autosmurf#25]
So I enjoy playing classic D2 more then LoD and been many many years since I've using bots for leveling, back when uber skeletons were op for lvling :D

I got everything set up but the bots keep progressing farther while under leveled and under geared. Is it possible to edit the level requirements of progressing and instead stay in normal / nightmare cs for longer?

**Comment by mf022** [comment]
https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/libs/bots/AutoSmurf.js#L16
https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/libs/bots/AutoSmurf.js#L21
