### ISSUE TITLE
人物设置了延时退出。会造成任务不同步。而无法继续。。。

### ISSUE THREAD

**Issue by wcg928** [blizzhackers/autosmurf#26]
人物设置了延时退出。会造成任务不同步。而无法继续。。。

**Comment by mf022** [comment]
[google translate](https://translate.google.com/?hl=en#view=home&op=translate&sl=auto&tl=en&text=%E4%BA%BA%E7%89%A9%E8%AE%BE%E7%BD%AE%E4%BA%86%E5%BB%B6%E6%97%B6%E9%80%80%E5%87%BA%E3%80%82%E4%BC%9A%E9%80%A0%E6%88%90%E4%BB%BB%E5%8A%A1%E4%B8%8D%E5%90%8C%E6%AD%A5%E3%80%82%E8%80%8C%E6%97%A0%E6%B3%95%E7%BB%A7%E7%BB%AD)The character set a delayed exit. Will cause tasks to be out of sync. And cannot continue
