### ISSUE TITLE
Updated Autosmurf by adpist

### ISSUE THREAD

**Issue by LAeRacing** [blizzhackers/autosmurf#28]
Here you can find an **updated/modifyed version** from adpist.
He made some nice changes and adds stuff like countess and fix alot of issues i personally recognised.

[https://cdn.discordapp.com/attachments/718181616421437440/718184554917003346/autosmurf_update.zip](url)

I just wanted to share this with you. Maye some developers can use this to improve the original one and add more stuff. 👍

**Comment by williamwangxiao** [comment]
cant download plz

**Comment by joeycozza** [comment]
> cant download plz

@williamwangxiao You can't just click the link here within Github for some reason. You need to copy the link, and paste it in the search bar. Then it should download just fine.
