### ISSUE TITLE
so what happened ,anyone can help me plz?

### ISSUE THREAD

**Issue by williamwangxiao** [blizzhackers/autosmurf#29]
I played with smurf  by 3 team mem was ok , but add to 5 member which will be wrong; error information can be seen as follow :
![QQ截图20200706130820](https://user-images.githubusercontent.com/67886505/86557980-8ff7df80-bf8a-11ea-8146-4a66ff1bac78.png)
so could some one help me solving this thanks

**Comment by mf022** [comment]
Do you have
```
	Config.WaypointMenu = true;
```
in the 5th char config?
