### ISSUE TITLE
stuck 

### ISSUE THREAD

**Issue by danteafk** [blizzhackers/autosmurf#31]
[08:35:59] <As2> Error in AutoSmurf (pather.js line 562): moveToPreset: Couldn't find preset unit - id 738
Stack: [default.dbj line 174](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/default.dbj#L174), [Loader.init lines:15-18](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Loader.js#L15-L18), [Loader.loadScripts line:124](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Loader.js#L124), [AutoSmurf line:5833](https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/libs/bots/AutoSmurf.js#L5833), [Autosmurf line 2510](https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/libs/bots/AutoSmurf.js#L2510), [Pather.moveToPreset ](https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Pather.js#L547-L575)

3 toons, all level 7.

all have the same wps up until dark wood, and are on the second quest for blood raven

they start by porting to cold plains, walk up until the burial grounds (dont even kill blood raven) and make a tp, then leader goes to dark forest, barb and second sorc stay at the top in cold plains/burial grounds.

**Comment by mf022** [comment]
Something is wrong in your config
