### ISSUE TITLE
My team of 4 keeps on making game at nightmare and stalls for 3 mins

### ISSUE THREAD

**Issue by j4sp3r89** [blizzhackers/autosmurf#33]
hi guys, i need some help.

My bot of 4 autosmurf, is currently at around lvl 60s. Now they are at a5 nightmare, and all they do is make a game, and stall for around 3 minutes, then they go to lobby, and this whole thing restart again. 

So what i did is, i added script for them to run diablo and baal every game. So now they are running diablo and baal... now they are already at level 75, 76, 75,74.

My question is, when will they start killing baal and move on to hell? can anyone guide me? im very new to this.

**Comment by postikus** [comment]
same here, i debugged a little and found out that thats because bot has no targets and stalling for min game time

**Comment by postikus** [comment]
ok noew i know how to fix it - u need enable in ur Sorcess.xxx.js etc
	Scripts.AutoSmurf = true;
then go to autosmurf.js and comment out 6101 - 6127 lines

// if (me.gametype === 1 && me.getQuest(39, 0) && ((me.diff == 1 && !this.partyLevel(baalLvlnm)) || me.diff == 2)) { //Dark-f
.......
// 	OnOff.disable("Scripts.AutoSmurf");
// })

**Comment by bruus4** [comment]
The problem is in AutoSmurf.js #6126
Uncomment this line, and enable Script.Autosmurf again in your character configs.

**Comment by mf022** [comment]
> So what i did is, i added script for them to run diablo and baal every game. So now they are running diablo and baal... now they are already at level 75, 76, 75,74.

have you check the setting in https://github.com/blizzhackers/autosmurf/blob/master/d2bs/kolbot/libs/bots/AutoSmurf.js#L22 ?
the default is 77th lvl to go to hell difficulty.

**Comment by gr33k** [comment]
If I may just clarify what @bruus4 stated (took me a while to mentally register it, so perhaps this helps you).

IF you are getting a stalled timer...check your character configs and verify that 

`Scripts.AutoSmurf = true;`

vs being = false; 

lol - That's all it was -  If it's getting disabled make sure your level minimums are adjusted in AutoSmurf.js and check line #6126 if necessary (mine is currently NOT commented out).

Thanks gentlemen!
