### ISSUE TITLE
How to use autosmurf for 8 bots

### ISSUE THREAD

**Issue by j4sp3r89** [blizzhackers/autosmurf#34]
Hi guys,

i have tried using 4 bots in 1 computer using autosmurf and successfully go to hell difficulty.
Im now thinking how to configure 8 bots running together in 1 game... 
i have 2 computer, 2 different ips. Can anyone guide me through? 

first computer, 4 bots with the leader as sorceress.
2nd computer, 4 bots all followers. But how do i make them join? is it through d2botchannel? haven tried it

**Comment by jstall6** [comment]
I know trhis doesnt help you but couold you tell me how to get the files to make auto smurf?

**Comment by mf022** [comment]
> 2nd computer, 4 bots all followers. But how do i make them join? is it through d2botchannel? haven tried it

maybe https://github.com/blizzhackers/documentation/blob/master/kolbot/MultiBotting.md/#d2botchannel could be an option
otherwise, on 2nd PC you could run a shared D2Bot from 1st PC.
maybe other choices could be ok.

**Comment by mf022** [comment]
> I know trhis doesnt help you but couold you tell me how to get the files to make auto smurf?

did you follow the [Readme file](https://github.com/blizzhackers/autosmurf#readme)?
