### ISSUE TITLE
Line:17 error (Config.AutoSmurf)

### ISSUE THREAD

**Issue by GeMiNiJaKe** [blizzhackers/autosmurf#4]
I don't understand what I'm doing wrong..Does it with all 3 profiles/chars and can't get them to party up to start walking and fighting

	Scripts.AutoSmurf = true;
		Config.AutoSmurf.TeamSize = 3;
		Config.AutoSmurf.TeleportingSorc = "GeMiNiGrL"; // your leader sorceress charname.
		Config.AutoSmurf.BoBarb = "GeMiNiBRuTe"; // boBarb charname
		Config.AutoSmurf.OtherChars = ["GeMiNiBRuTe", "GeMiNiNoaH"]; // all team charnames, excluding the leader and boBarb
		Config.AutoSmurf.AllTeamProfiles = ["GrL","BRuTe","NoaH"]; // the whole team PROFILE names

**Comment by GeMiNiJaKe** [comment]
P.S. all new chars

**Comment by mf022** [comment]
> Config.AutoSmurf.OtherChars = ["GeMiNiBRuTe", "GeMiNiNoaH"]; // all team charnames, excluding the leader and boBarb

exclude the BoBarb, like the TeleportingSorceress
Config.AutoSmurf.OtherChars = ["GeMiNiNoaH"]; 

Did you renamed correctly the required chars *.xxx1, especially for your leader Sorceress.XXXX1(leader).js

Re-check the // Public game options section. The leader should invite, so it need 1 or 3
```
Config.PublicMode = 1;
```
the followers should only accept the invitations, so 2.

**Comment by GeMiNiJaKe** [comment]
All characters are labeled right, Sorceress.GeMiNiGrL, Paladin.GeMiNiNoaH, Barbarian.GeMiNiBRuTe exactly how I had created the characters and still getting the Line:17. Doesn't seem to like 

"Config.AutoSmurf.TeamSize = 3;" cause that's the 17th line

**Comment by GeMiNiJaKe** [comment]
I'd send you a screen shot of my screen but can't add attachments lol

**Comment by mf022** [comment]
Did you corrected what I've already suggested?
your 20th line was wrong, with BoBarb
Did you check the Config.PublicMode for each char?

maybe you can add only a link. post it to image host sites.

**Comment by GeMiNiJaKe** [comment]
Scripts.AutoSmurf = true;
		Config.AutoSmurf.TeamSize = 3;
		Config.AutoSmurf.TeleportingSorc = ""; // your leader sorceress charname.
		Config.AutoSmurf.BoBarb = ""; // boBarb charname
		Config.AutoSmurf.OtherChars = ["GeMiNiNoaH"]; // all team charnames, excluding the leader and boBarb
		Config.AutoSmurf.AllTeamProfiles = ["GeMiNiGrL","GeMiNiBRuTe", "GeMiNiNoaH"]; // the whole team PROFILE names

that's how it is now after the changes, and not yet more concerned with the Line:17 lol

**Comment by GeMiNiJaKe** [comment]
I mean I've been running the Kolbot in public d/baal runs on ladder before reset, but this is just stumping me like crazy

**Comment by mf022** [comment]
do no mix char and profile names (line 21)

read the descriptions.

the char names of teleportingSorceress and BoBarb should be there

follow the [guide](https://github.com/blizzhackers/autosmurf#autosmurf)

**Comment by GeMiNiJaKe** [comment]
Scripts.AutoSmurf = true;
		Config.AutoSmurf.TeamSize = 3;
		Config.AutoSmurf.TeleportingSorc = "GeMiNiGrL"; // your leader sorceress charname.
		Config.AutoSmurf.BoBarb = "GeMiNiBRuTe"; // boBarb charname
		Config.AutoSmurf.OtherChars = ["GeMiNiNoaH"]; // all team charnames, excluding the leader and boBarb
		Config.AutoSmurf.AllTeamProfiles = ["GrL","BRuTe","NoaH"]; // the whole team PROFILE names

P.S. "GrL","BRuTe","NoaH" are my profile names

**Comment by GeMiNiJaKe** [comment]
[https://ibb.co/GF7mb93](url)

[https://ibb.co/wRvfKCh](url)

**Comment by GeMiNiJaKe** [comment]
<a href="https://ibb.co/wRvfKCh"><img src="https://i.ibb.co/wRvfKCh/79095509-2631151427122491-3374213371019657216-n.jpg" alt="79095509-2631151427122491-3374213371019657216-n" border="0"></a> <a href="https://ibb.co/GF7mb93"><img src="https://i.ibb.co/GF7mb93/78605533-2420675804848141-1889295807874596864-n.jpg" alt="78605533-2420675804848141-1889295807874596864-n" border="0"></a>

**Comment by GeMiNiJaKe** [comment]
Man I dunno wtf happened but I had completely deleted the entire bot and redownloaded and config and now it working like a charm

**Comment by mf022** [comment]
the problem was in your Config.js, before you haven't the variables for Autosmurf.
