### ISSUE TITLE
All bots stopped at level 30, now they walk to an act 5 npc, and open and close talking dialogue.

### ISSUE THREAD

**Issue by Jtech42** [blizzhackers/autosmurf#8]
Anyone seen this before? I've seen them standing and talking to Larzuk when they all have mercs, and I have seen them all just standing in front of Mala opening up her talk and sale options and just closing them over and over.

**Comment by mf022** [comment]
Did you changed something for latest autosmurf team?

**Comment by Jtech42** [comment]
I don't think so went pretty standard by the docs, restarting and seemed to fix the issue and they grinded in normal to 42 before getting a temp timeout for making games too fast. Great tool!

**Comment by mf022** [comment]
> restarting and seemed to fix the issue

maybe that was a bug due to lag connection on d2 server.

good thing is that it is working for you now.
maybe you should increase the timers like Config.MinGameTime, MinGameTime: rand(150, 180), ...
