### ISSUE TITLE
Script error 222 bobarb undefined

### ISSUE THREAD

**Issue by tADDEH** [blizzhackers/autosmurf#9]
Hi!

Can't wait to get this working, Brand new SVN version of Kolbot copied all the files over from autosmurf, configs setup as the guide/darc YouTube also.

They all join the game as expected but it stops with the error:

_[Strict Warning (162)] File(kolbot\default.dbj:166) reference to undefined property Config.BoBarbHelper
[Error(222)] File(kolbotdefault.dbj:166) TypeError:Config.BoBarbHelper is undefined_

Looking through the files all seems to be there and looking at the current version?

Thanks

**Comment by tADDEH** [comment]
Looks like an issues with the latest trunk, downloaded the previous revision and it appears to be working as expected now?

**Comment by mf022** [comment]
> [Strict Warning (162)] File(kolbot\default.dbj:166) reference to undefined property Config.BoBarbHelper
> [Error(222)] File(kolbotdefault.dbj:166) TypeError:Config.BoBarbHelper is undefined

Config js wasn't updated yet with these lines https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Config.js#L445-L449

the easy way was to add autosmurf lines from guide to the end of default Config.js

**Comment by mf022** [comment]
https://github.com/blizzhackers/autosmurf/commit/4666bc5f5cec6da22adb1612b27b0f6ad5079542
